<?php

return [
    'homepage'=>[
        'dashboard'=>'builder/home/dashboard',
    ],
    'pendataan'=>[
        'dbkb'=>[
            'dbkb-utama'=>'builder/dbkb-utama/index',
            'dbkb-material'=>'builder/dbkb-material/index',
            'dbkb-fasilitas'=>'builder/dbkb-fasilitas/index',
            'dbkb-utama-material'=>'builder/dbkb-utama-material/index',
        ],
        'znt'=>[
            'nir'=>'builder/nir/index',
            'nama-jalan'=>'builder/nama-jalan/index',
            'znt'=>'builder/znt/index',
            'blok'=>'builder/blok/index',
        ],
        'objek-pajak'=>[
            'objek-pajak-bumi'=>'builder/objek-pajak-bumi/index',
            'objek-pajak-bangunan'=>'builder/objek-pajak-bangunan/index',
        ],
        'subjek-pajak'=>'builder/subjek-pajak/index',
    ],
    'penilaian'=>[
        'penilaian-massal'=>'builder/penilaian-massal/index',
        'laporan-penilaian'=>[
            'perbandingan'=>'builder/penilaian/laporan/perbandingan',
            'bumi'=>'builder/penilaian/laporan/bumi',
            'bangunan'=>'builder/penilaian/laporan/bangunan',
            'perbandingan-penilaian-bumi-dan-bangunan'=>'builder/penilaian/laporan/perbandingan-penilaian-bumi-dan-bangunan/index'
        ]
    ],
    'penetapan'=>[
        'pbb-minimal'=>'builder/pbb-minimal/index',
        'penetapan-njoptkp'=>'builder/penetapan-njoptkp/index',
        'penetapan-sppt-massal'=>'builder/penetapan-sppt-massal/index',
        'penetapan-sppt-tunggal'=>'builder/penetapan-sppt-tunggal/index',
        'pelunasan-massal'=>'builder/pelunasan-massal/index',
        'pelunasan-tunggal'=>'builder/pelunasan-tunggal/index',
    ],
    'referensi'=>[
        'wilayah'=>[
            'kecamatan'=>'builder/kecamatan/index',
            'kelurahan'=>'builder/kelurahan/index',
        ],
        'tempat-pembayaran'=>'builder/tempat-pembayaran/index',
        'kayu-ulin'=>'builder/kayu-ulin/index',
        'update-resources'=>'builder/update-resources/index',
        'posting-sppt-lama'=>'builder/posting-sppt-lama/index',
    ],
    'laporan'=>[
        'sppt'=>'builder/laporan/sppt/index',
        'sspd'=>'builder/laporan/sspd/index',
        'dhkp'=>'builder/laporan/dhkp/index',
        'klasifikasi-dan-besaran-njop-bumi'=>'builder/laporan/klasifikasi-dan-besaran-njop-bumi/index',
        'dbkb'=>'builder/laporan/dbkb/index',
        'simulasi-penetapan-sppt'=>'builder/laporan/simulasi-penetapan-sppt/index',
    ],
    'penatausahaan'=>[
        'laporan-realisasi'=>'builder/penatausahaan/laporan-realisasi/index',
        'laporan-piutang'=>'builder/penatausahaan/laporan-piutang/index',
        'surat-tagihan'=>'builder/penatausahaan/surat-tagihan/index',
        'status-wajib-pajak'=>'builder/penatausahaan/status-wajib-pajak/index',
        'log-perubahan-objek'=>'builder/penatausahaan/log-perubahan-objek/index',
        'log-objek-baru'=>'builder/penatausahaan/log-objek-baru/index',
    ],
    'utility'=>[
        'roles'=>'builder/roles/index',
        'users'=>'builder/users/index',
        'pejabat'=>'builder/pejabat/index',
    ],
];