<?php

return [
    'homepage'=>[
        'dashboard'=>'builder/home/dashboard',
    ],
    'pendataan'=>[
        'dbkb'=>[
            'dbkb-utama'=>'builder/dbkb-utama/index',
            'dbkb-material'=>'builder/dbkb-material/index',
            'dbkb-fasilitas'=>'builder/dbkb-fasilitas/index',
            'dbkb-utama-material'=>'builder/dbkb-utama-material/index',
        ],
        'znt'=>[
            'nir'=>'builder/nir/index',
            'nama-jalan'=>'builder/nama-jalan/index',
            'znt'=>'builder/znt/index',
            'blok'=>'builder/blok/index',
        ],
        'objek-pajak'=>[
            'objek-pajak-bumi'=>'builder/objek-pajak-bumi/index',
            'objek-pajak-bangunan'=>'builder/objek-pajak-bangunan/index',
        ],
        'subjek-pajak'=>'builder/subjek-pajak/index',
    ],
    'penilaian'=>[
        'penilaian-massal'=>'builder/penilaian-massal/index',
        'laporan-penilaian'=>[
            'perbandingan'=>'builder/penilaian/laporan/perbandingan',
            'bumi'=>'builder/penilaian/laporan/bumi',
            'bangunan'=>'builder/penilaian/laporan/bangunan'
        ]
    ],
    'penetapan'=>[
        'pbb-minimal'=>'builder/pbb-minimal/index',
        'penetapan-njoptkp'=>'builder/penetapan-njoptkp/index',
        'penetapan-sppt'=>'builder/penetapan-sppt/index',
        'pelunasan'=>'builder/pelunasan/index',
    ],
    'referensi'=>[
        'wilayah'=>[
            'kecamatan'=>'builder/kecamatan/index',
            'kelurahan'=>'builder/kelurahan/index',
        ],
        'tempat-pembayaran'=>'builder/tempat-pembayaran/index',
        'kayu-ulin'=>'builder/kayu-ulin/index',
    ],
    'laporan'=>[
        'sppt'=>'builder/laporan/sppt/index',
    ],
    'utility'=>[
        'roles'=>'builder/roles/index',
        'users'=>'builder/users/index',
        'pejabat'=>'builder/pejabat/index',
    ],
];