<?php

require '../helpers/QueryBuilder.php';

$qb = new QueryBuilder();

extract($_GET);

if(($KD_KECAMATAN == 'Semua' || $KD_KECAMATAN == '')  && ($KD_KELURAHAN == 'Semua' || $KD_KELURAHAN == ''))
{

    // $C_STR = "SELECT 
    //         DAT_OBJEK_PAJAK.KD_PROPINSI, 
    //         DAT_OBJEK_PAJAK.KD_DATI2, 
    //         DAT_OBJEK_PAJAK.KD_Kecamatan, 
    //         DAT_OBJEK_PAJAK.KD_KELURAHAN, 
    //         DAT_OP_BUMI.KD_BLOK, 
    //         DAT_OP_BUMI.NO_URUT, 
    //         DAT_OP_BUMI.KD_JNS_OP, 
    //         DAT_OP_BUMI.NO_BUMI, 
    //         DAT_OBJEK_PAJAK.TOTAL_LUAS_BUMI, 
    //         REF_KECAMATAN.NM_KECAMATAN, 
    //         REF_KELURAHAN.NM_KELURAHAN, 
    //         DAT_OP_BUMI.NILAI_SISTEM_BUMI, 
    //         Count(DAT_OP_BANGUNAN.NO_BNG) AS JUM_BNG, 
    //         Sum(DAT_OP_BANGUNAN.LUAS_BNG) AS TOT_LUAS_BNG, 
    //         Sum(DAT_OP_BANGUNAN.NILAI_SISTEM_BNG) AS TOT_NILAI_BNG,
    //         '" . $tahun_pajak . "' as TAHUN 
    //     FROM 
    //     (
    //         (
    //             (DAT_OBJEK_PAJAK INNER JOIN REF_KECAMATAN ON DAT_OBJEK_PAJAK.KD_KECAMATAN = REF_KECAMATAN.KD_KECAMATAN) " . 
                
    //             " INNER JOIN REF_KELURAHAN ON 
    //                 (DAT_OBJEK_PAJAK.KD_KECAMATAN = REF_KELURAHAN.KD_KECAMATAN) AND 
    //                 (DAT_OBJEK_PAJAK.KD_KELURAHAN = REF_KELURAHAN.KD_KELURAHAN)

    //         ) 
            
    //         INNER JOIN DAT_OP_BUMI ON 
    //             (DAT_OBJEK_PAJAK.KD_PROPINSI = DAT_OP_BUMI.KD_PROPINSI) AND 
    //             (DAT_OBJEK_PAJAK.KD_DATI2 = DAT_OP_BUMI.KD_DATI2) AND 
    //             (DAT_OBJEK_PAJAK.KD_KECAMATAN = DAT_OP_BUMI.KD_KECAMATAN) AND 
    //             (DAT_OBJEK_PAJAK.KD_KELURAHAN = DAT_OP_BUMI.KD_KELURAHAN) AND 
    //             (DAT_OBJEK_PAJAK.KD_BLOK = DAT_OP_BUMI.KD_BLOK) AND 
    //             (DAT_OBJEK_PAJAK.NO_URUT = DAT_OP_BUMI.NO_URUT) AND 
    //             (DAT_OBJEK_PAJAK.KD_JNS_OP = DAT_OP_BUMI.KD_JNS_OP))" . 
                
    //         " LEFT JOIN DAT_OP_BANGUNAN ON 
    //             (DAT_OBJEK_PAJAK.KD_PROPINSI = DAT_OP_BANGUNAN.KD_PROPINSI) AND 
    //             (DAT_OBJEK_PAJAK.KD_DATI2 = DAT_OP_BANGUNAN.KD_DATI2) AND 
    //             (DAT_OBJEK_PAJAK.KD_KECAMATAN = DAT_OP_BANGUNAN.KD_KECAMATAN) AND 
    //             (DAT_OBJEK_PAJAK.KD_KELURAHAN = DAT_OP_BANGUNAN.KD_KELURAHAN) AND 
    //             (DAT_OBJEK_PAJAK.KD_BLOK = DAT_OP_BANGUNAN.KD_BLOK) AND 
    //             (DAT_OBJEK_PAJAK.NO_URUT = DAT_OP_BANGUNAN.NO_URUT) AND 
    //             (DAT_OBJEK_PAJAK.KD_JNS_OP = DAT_OP_BANGUNAN.KD_JNS_OP) " . 
                
    //         " GROUP BY 
    //             DAT_OBJEK_PAJAK.KD_PROPINSI, 
    //             DAT_OBJEK_PAJAK.KD_DATI2, 
    //             DAT_OBJEK_PAJAK.KD_Kecamatan, 
    //             DAT_OBJEK_PAJAK.KD_KELURAHAN, 
    //             DAT_OP_BUMI.KD_BLOK, 
    //             DAT_OP_BUMI.NO_URUT, 
    //             DAT_OP_BUMI.KD_JNS_OP, 
    //             DAT_OP_BUMI.NO_BUMI, 
    //             DAT_OBJEK_PAJAK.TOTAL_LUAS_BUMI, 
    //             REF_KECAMATAN.NM_KECAMATAN, 
    //             REF_KELURAHAN.NM_KELURAHAN, 
    //             DAT_OP_BUMI.NILAI_SISTEM_BUMI UNION ALL " . 
            
    //         "SELECT 

    //             C_OBJEK.KD_PROPINSI, 
    //             C_OBJEK.KD_DATI2, 
    //             C_OBJEK.KD_Kecamatan,
    //             C_OBJEK.KD_KELURAHAN,
    //             C_OBJEK.KD_BLOK,
    //             C_OBJEK.NO_URUT,
    //             C_OBJEK.KD_JNS_OP,
    //             C_BUMI.NO_BUMI,
    //             C_OBJEK.TOTAL_LUAS_BUMI,
    //             REF_KECAMATAN.NM_KECAMATAN,
    //             REF_KELURAHAN.NM_KELURAHAN,
    //             C_BUMI.NILAI_SISTEM_BUMI,
    //             Count(C_BANGUNAN.NO_BNG) AS JUM_BNG,
    //             Sum(C_BANGUNAN.LUAS_BNG) AS TOT_LUAS_BNG,
    //             Sum(C_BANGUNAN.NILAI_SISTEM_BNG) AS TOT_NILAI_BNG,
    //             '" . ($tahun_pajak-1) . "' as TAHUN 
                
    //         FROM 

    //             (
    //                 (
    //                     (C_OBJEK INNER JOIN REF_KECAMATAN ON C_OBJEK.KD_KECAMATAN = REF_KECAMATAN.KD_KECAMATAN)" . 
    //                     " INNER JOIN REF_KELURAHAN ON 
    //                         (C_OBJEK.KD_KECAMATAN = REF_KELURAHAN.KD_KECAMATAN) AND 
    //                         (C_OBJEK.KD_KELURAHAN = REF_KELURAHAN.KD_KELURAHAN)
    //                 ) 

    //                 INNER JOIN C_BUMI ON 
    //                     (C_OBJEK.KD_KECAMATAN = C_BUMI.KD_KECAMATAN) AND 
    //                     (C_OBJEK.KD_KELURAHAN = C_BUMI.KD_KELURAHAN) AND 
    //                     (C_OBJEK.KD_BLOK = C_BUMI.KD_BLOK) AND 
    //                     (C_OBJEK.NO_URUT = C_BUMI.NO_URUT) AND 
    //                     (C_OBJEK.KD_JNS_OP = C_BUMI.KD_JNS_OP)
    //             ) 
                    
    //             LEFT JOIN C_BANGUNAN ON 
    //                 (C_OBJEK.KD_KECAMATAN = C_BANGUNAN.KD_KECAMATAN) AND 
    //                 (C_OBJEK.KD_KELURAHAN = C_BANGUNAN.KD_KELURAHAN) AND 
    //                 (C_OBJEK.KD_BLOK = C_BANGUNAN.KD_BLOK) AND 
    //                 (C_OBJEK.NO_URUT = C_BANGUNAN.NO_URUT) AND 
    //                 (C_OBJEK.KD_JNS_OP = C_BANGUNAN.KD_JNS_OP)" . 
                
    //             " GROUP BY 
    //                 C_OBJEK.KD_PROPINSI, 
    //                 C_OBJEK.KD_DATI2, 
    //                 C_OBJEK.KD_Kecamatan, 
    //                 C_OBJEK.KD_KELURAHAN, 
    //                 C_OBJEK.KD_BLOK, 
    //                 C_OBJEK.NO_URUT, 
    //                 C_OBJEK.KD_JNS_OP, 
    //                 C_BUMI.NO_BUMI, 
    //                 C_OBJEK.TOTAL_LUAS_BUMI, 
    //                 REF_KECAMATAN.NM_KECAMATAN, 
    //                 REF_KELURAHAN.NM_KELURAHAN, 
    //                 C_BUMI.NILAI_SISTEM_BUMI";


    // EDITED

//     SELECT 
	
// 	KD_PROPINSI,KD_DATI2,KD_KECAMATAN,KD_KELURAHAN,KD_BLOK,NO_URUT,KD_JNS_OP,

// 	NO_BUMI,

// 	NM_KECAMATAN,NM_KELURAHAN,

// 	sum(NILAI_SISTEM_BUMI) as NILAI_SISTEM_BUMI,

// 	TOTAL_LUAS_BUMI,

// 	count(JUM_BNG) as JUM_BNG,
// 	sum(TOT_LUAS_BNG) as TOT_LUAS_BNG,
// 	sum(TOT_NILAI_BNG) as TOT_NILAI_BNG

// FROM

// (
// 	SELECT 

// 		DAT_OBJEK_PAJAK.KD_PROPINSI, 
// 		DAT_OBJEK_PAJAK.KD_DATI2, 
// 		DAT_OBJEK_PAJAK.KD_Kecamatan, 
// 		DAT_OBJEK_PAJAK.KD_KELURAHAN, 
// 		DAT_OBJEK_PAJAK.TOTAL_LUAS_BUMI, 

// 		DAT_OP_BUMI.KD_BLOK, 
// 		DAT_OP_BUMI.NO_URUT, 
// 		DAT_OP_BUMI.KD_JNS_OP, 
// 		DAT_OP_BUMI.NO_BUMI, 

// 		REF_KECAMATAN.NM_KECAMATAN, 
// 		REF_KELURAHAN.NM_KELURAHAN, 
// 		DAT_OP_BUMI.NILAI_SISTEM_BUMI,
		
// 		Count(DAT_OP_BANGUNAN.NO_BNG) AS JUM_BNG, 
// 		Sum(DAT_OP_BANGUNAN.LUAS_BNG) AS TOT_LUAS_BNG, 
// 		Sum(DAT_OP_BANGUNAN.NILAI_SISTEM_BNG) AS TOT_NILAI_BNG,

// 		'2021' as TAHUN 

// 	FROM 

// 		DAT_OBJEK_PAJAK

// 			INNER JOIN REF_KECAMATAN ON 
// 				(DAT_OBJEK_PAJAK.KD_KECAMATAN = REF_KECAMATAN.KD_KECAMATAN)
		
// 			INNER JOIN REF_KELURAHAN ON 
// 				(DAT_OBJEK_PAJAK.KD_KECAMATAN = REF_KELURAHAN.KD_KECAMATAN) AND 
// 				(DAT_OBJEK_PAJAK.KD_KELURAHAN = REF_KELURAHAN.KD_KELURAHAN)
            
// 			INNER JOIN DAT_OP_BUMI ON 
// 				(DAT_OBJEK_PAJAK.KD_PROPINSI = DAT_OP_BUMI.KD_PROPINSI) AND 
// 				(DAT_OBJEK_PAJAK.KD_DATI2 = DAT_OP_BUMI.KD_DATI2) AND 
// 				(DAT_OBJEK_PAJAK.KD_KECAMATAN = DAT_OP_BUMI.KD_KECAMATAN) AND 
// 				(DAT_OBJEK_PAJAK.KD_KELURAHAN = DAT_OP_BUMI.KD_KELURAHAN) AND 
// 				(DAT_OBJEK_PAJAK.KD_BLOK = DAT_OP_BUMI.KD_BLOK) AND 
// 				(DAT_OBJEK_PAJAK.NO_URUT = DAT_OP_BUMI.NO_URUT) AND 
// 				(DAT_OBJEK_PAJAK.KD_JNS_OP = DAT_OP_BUMI.KD_JNS_OP)

// 			LEFT JOIN DAT_OP_BANGUNAN ON 
// 				(DAT_OBJEK_PAJAK.KD_PROPINSI = DAT_OP_BANGUNAN.KD_PROPINSI) AND 
// 				(DAT_OBJEK_PAJAK.KD_DATI2 = DAT_OP_BANGUNAN.KD_DATI2) AND 
// 				(DAT_OBJEK_PAJAK.KD_KECAMATAN = DAT_OP_BANGUNAN.KD_KECAMATAN) AND 
// 				(DAT_OBJEK_PAJAK.KD_KELURAHAN = DAT_OP_BANGUNAN.KD_KELURAHAN) AND 
// 				(DAT_OBJEK_PAJAK.KD_BLOK = DAT_OP_BANGUNAN.KD_BLOK) AND 
// 				(DAT_OBJEK_PAJAK.NO_URUT = DAT_OP_BANGUNAN.NO_URUT) AND 
// 				(DAT_OBJEK_PAJAK.KD_JNS_OP = DAT_OP_BANGUNAN.KD_JNS_OP)  

// 		GROUP BY 
// 			DAT_OBJEK_PAJAK.KD_PROPINSI, 
// 			DAT_OBJEK_PAJAK.KD_DATI2, 
// 			DAT_OBJEK_PAJAK.KD_Kecamatan, 
// 			DAT_OBJEK_PAJAK.KD_KELURAHAN, 
// 			DAT_OBJEK_PAJAK.TOTAL_LUAS_BUMI,

// 			DAT_OP_BUMI.KD_BLOK, 
// 			DAT_OP_BUMI.NO_URUT, 
// 			DAT_OP_BUMI.KD_JNS_OP, 
// 			DAT_OP_BUMI.NO_BUMI, 

// 			REF_KECAMATAN.NM_KECAMATAN, 
// 			REF_KELURAHAN.NM_KELURAHAN, 

// 			DAT_OP_BUMI.NILAI_SISTEM_BUMI 

// 	UNION ALL

// 	SELECT 

// 		C_OBJEK.KD_PROPINSI, 
// 		C_OBJEK.KD_DATI2, 
// 		C_OBJEK.KD_Kecamatan,
// 		C_OBJEK.KD_KELURAHAN,
// 		C_OBJEK.KD_BLOK,
// 		C_OBJEK.NO_URUT,
// 		C_OBJEK.KD_JNS_OP,

// 		C_BUMI.NO_BUMI,
    
// 		C_OBJEK.TOTAL_LUAS_BUMI,

// 		REF_KECAMATAN.NM_KECAMATAN,
// 		REF_KELURAHAN.NM_KELURAHAN,
    
// 		C_BUMI.NILAI_SISTEM_BUMI,
    
// 		Count(C_BANGUNAN.NO_BNG) AS JUM_BNG,
// 		Sum(C_BANGUNAN.LUAS_BNG) AS TOT_LUAS_BNG,
// 		Sum(C_BANGUNAN.NILAI_SISTEM_BNG) AS TOT_NILAI_BNG,
// 		'2020' as TAHUN 
                
// 	FROM 
           
// 		C_OBJEK 
				
// 			INNER JOIN REF_KECAMATAN ON 
// 				(C_OBJEK.KD_KECAMATAN = REF_KECAMATAN.KD_KECAMATAN)

// 			INNER JOIN REF_KELURAHAN ON 
// 				(C_OBJEK.KD_KECAMATAN = REF_KELURAHAN.KD_KECAMATAN) AND 
// 				(C_OBJEK.KD_KELURAHAN = REF_KELURAHAN.KD_KELURAHAN)

// 			INNER JOIN C_BUMI ON 
// 				(C_OBJEK.KD_KECAMATAN = C_BUMI.KD_KECAMATAN) AND 
// 				(C_OBJEK.KD_KELURAHAN = C_BUMI.KD_KELURAHAN) AND 
// 				(C_OBJEK.KD_BLOK = C_BUMI.KD_BLOK) AND 
// 				(C_OBJEK.NO_URUT = C_BUMI.NO_URUT) AND 
// 				(C_OBJEK.KD_JNS_OP = C_BUMI.KD_JNS_OP)
		
// 			LEFT JOIN C_BANGUNAN ON 
// 				(C_OBJEK.KD_KECAMATAN = C_BANGUNAN.KD_KECAMATAN) AND 
// 				(C_OBJEK.KD_KELURAHAN = C_BANGUNAN.KD_KELURAHAN) AND 
// 				(C_OBJEK.KD_BLOK = C_BANGUNAN.KD_BLOK) AND 
// 				(C_OBJEK.NO_URUT = C_BANGUNAN.NO_URUT) AND 
// 				(C_OBJEK.KD_JNS_OP = C_BANGUNAN.KD_JNS_OP)
		
// 		GROUP BY 
// 			C_OBJEK.KD_PROPINSI, 
// 			C_OBJEK.KD_DATI2, 
// 			C_OBJEK.KD_Kecamatan, 
// 			C_OBJEK.KD_KELURAHAN, 
// 			C_OBJEK.KD_BLOK, 
// 			C_OBJEK.NO_URUT, 
// 			C_OBJEK.KD_JNS_OP, 
        
// 			C_BUMI.NO_BUMI, 
        
// 			C_OBJEK.TOTAL_LUAS_BUMI, 
        
// 			REF_KECAMATAN.NM_KECAMATAN, 
// 			REF_KELURAHAN.NM_KELURAHAN, 
        
// 			C_BUMI.NILAI_SISTEM_BUMI

// ) t 

// GROUP BY 
// 	KD_PROPINSI, 
//     KD_DATI2, 
//     KD_Kecamatan, 
//     KD_KELURAHAN, 
//     TOTAL_LUAS_BUMI,

//     KD_BLOK, 
//     NO_URUT, 
//     KD_JNS_OP, 
//     NO_BUMI, 

//     NM_KECAMATAN, 
//     NM_KELURAHAN, 

//     NILAI_SISTEM_BUMI

    $C_STR = "SELECT DAT_OBJEK_PAJAK.KD_PROPINSI, DAT_OBJEK_PAJAK.KD_DATI2, DAT_OBJEK_PAJAK.KD_Kecamatan, DAT_OBJEK_PAJAK.KD_KELURAHAN, DAT_OP_BUMI.KD_BLOK, DAT_OP_BUMI.NO_URUT, DAT_OP_BUMI.KD_JNS_OP, DAT_OP_BUMI.NO_BUMI, DAT_OBJEK_PAJAK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, DAT_OP_BUMI.NILAI_SISTEM_BUMI, Count(DAT_OP_BANGUNAN.NO_BNG) AS JUM_BNG, Sum(DAT_OP_BANGUNAN.LUAS_BNG) AS TOT_LUAS_BNG, Sum(DAT_OP_BANGUNAN.NILAI_SISTEM_BNG) AS TOT_NILAI_BNG,'" . $tahun_pajak . "' as TAHUN FROM (((DAT_OBJEK_PAJAK INNER JOIN REF_KECAMATAN ON DAT_OBJEK_PAJAK.KD_KECAMATAN = REF_KECAMATAN.KD_KECAMATAN) " . "INNER JOIN REF_KELURAHAN ON (DAT_OBJEK_PAJAK.KD_KECAMATAN = REF_KELURAHAN.KD_KECAMATAN) AND (DAT_OBJEK_PAJAK.KD_KELURAHAN = REF_KELURAHAN.KD_KELURAHAN)) INNER JOIN DAT_OP_BUMI ON (DAT_OBJEK_PAJAK.KD_PROPINSI = DAT_OP_BUMI.KD_PROPINSI) AND (DAT_OBJEK_PAJAK.KD_DATI2 = DAT_OP_BUMI.KD_DATI2) AND (DAT_OBJEK_PAJAK.KD_KECAMATAN = DAT_OP_BUMI.KD_KECAMATAN) AND (DAT_OBJEK_PAJAK.KD_KELURAHAN = DAT_OP_BUMI.KD_KELURAHAN) AND (DAT_OBJEK_PAJAK.KD_BLOK = DAT_OP_BUMI.KD_BLOK) AND (DAT_OBJEK_PAJAK.NO_URUT = DAT_OP_BUMI.NO_URUT) AND (DAT_OBJEK_PAJAK.KD_JNS_OP = DAT_OP_BUMI.KD_JNS_OP))" . "LEFT JOIN DAT_OP_BANGUNAN ON (DAT_OBJEK_PAJAK.KD_PROPINSI = DAT_OP_BANGUNAN.KD_PROPINSI) AND (DAT_OBJEK_PAJAK.KD_DATI2 = DAT_OP_BANGUNAN.KD_DATI2) AND (DAT_OBJEK_PAJAK.KD_KECAMATAN = DAT_OP_BANGUNAN.KD_KECAMATAN) AND (DAT_OBJEK_PAJAK.KD_KELURAHAN = DAT_OP_BANGUNAN.KD_KELURAHAN) AND (DAT_OBJEK_PAJAK.KD_BLOK = DAT_OP_BANGUNAN.KD_BLOK) AND (DAT_OBJEK_PAJAK.NO_URUT = DAT_OP_BANGUNAN.NO_URUT) AND (DAT_OBJEK_PAJAK.KD_JNS_OP = DAT_OP_BANGUNAN.KD_JNS_OP) " . "GROUP BY DAT_OBJEK_PAJAK.KD_PROPINSI, DAT_OBJEK_PAJAK.KD_DATI2, DAT_OBJEK_PAJAK.KD_Kecamatan, DAT_OBJEK_PAJAK.KD_KELURAHAN, DAT_OP_BUMI.KD_BLOK, DAT_OP_BUMI.NO_URUT, DAT_OP_BUMI.KD_JNS_OP, DAT_OP_BUMI.NO_BUMI, DAT_OBJEK_PAJAK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, DAT_OP_BUMI.NILAI_SISTEM_BUMI UNION ALL " . "SELECT C_OBJEK.KD_PROPINSI, C_OBJEK.KD_DATI2, C_OBJEK.KD_Kecamatan, C_OBJEK.KD_KELURAHAN, C_OBJEK.KD_BLOK, C_OBJEK.NO_URUT, C_OBJEK.KD_JNS_OP, C_BUMI.NO_BUMI, C_OBJEK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, C_BUMI.NILAI_SISTEM_BUMI, Count(C_BANGUNAN.NO_BNG) AS JUM_BNG, Sum(C_BANGUNAN.LUAS_BNG) AS TOT_LUAS_BNG, Sum(C_BANGUNAN.NILAI_SISTEM_BNG) AS TOT_NILAI_BNG,'" . ($tahun_pajak - 1) . "' as TAHUN FROM (((C_OBJEK INNER JOIN REF_KECAMATAN ON C_OBJEK.KD_KECAMATAN = REF_KECAMATAN.KD_KECAMATAN)" . "INNER JOIN REF_KELURAHAN ON (C_OBJEK.KD_KECAMATAN = REF_KELURAHAN.KD_KECAMATAN) AND (C_OBJEK.KD_KELURAHAN = REF_KELURAHAN.KD_KELURAHAN)) INNER JOIN C_BUMI ON (C_OBJEK.KD_KECAMATAN = C_BUMI.KD_KECAMATAN) AND (C_OBJEK.KD_KELURAHAN = C_BUMI.KD_KELURAHAN) AND (C_OBJEK.KD_BLOK = C_BUMI.KD_BLOK) AND (C_OBJEK.NO_URUT = C_BUMI.NO_URUT) AND (C_OBJEK.KD_JNS_OP = C_BUMI.KD_JNS_OP)) LEFT JOIN C_BANGUNAN ON (C_OBJEK.KD_KECAMATAN = C_BANGUNAN.KD_KECAMATAN) AND (C_OBJEK.KD_KELURAHAN = C_BANGUNAN.KD_KELURAHAN) AND (C_OBJEK.KD_BLOK = C_BANGUNAN.KD_BLOK) AND (C_OBJEK.NO_URUT = C_BANGUNAN.NO_URUT) AND (C_OBJEK.KD_JNS_OP = C_BANGUNAN.KD_JNS_OP)" . "GROUP BY C_OBJEK.KD_PROPINSI, C_OBJEK.KD_DATI2, C_OBJEK.KD_Kecamatan, C_OBJEK.KD_KELURAHAN, C_OBJEK.KD_BLOK, C_OBJEK.NO_URUT, C_OBJEK.KD_JNS_OP, C_BUMI.NO_BUMI, C_OBJEK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, C_BUMI.NILAI_SISTEM_BUMI";


}
elseif($KD_KECAMATAN != 'Semua' && ($KD_KELURAHAN == 'Semua' || $KD_KELURAHAN == ''))
{

    $C_STR = "SELECT DAT_OBJEK_PAJAK.KD_PROPINSI, 
    DAT_OBJEK_PAJAK.KD_DATI2, DAT_OBJEK_PAJAK.KD_Kecamatan, DAT_OBJEK_PAJAK.KD_KELURAHAN, DAT_OP_BUMI.KD_BLOK, DAT_OP_BUMI.NO_URUT, DAT_OP_BUMI.KD_JNS_OP, DAT_OP_BUMI.NO_BUMI, DAT_OBJEK_PAJAK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, DAT_OP_BUMI.NILAI_SISTEM_BUMI, Count(DAT_OP_BANGUNAN.NO_BNG) AS JUM_BNG, Sum(DAT_OP_BANGUNAN.LUAS_BNG) AS TOT_LUAS_BNG, Sum(DAT_OP_BANGUNAN.NILAI_SISTEM_BNG) AS TOT_NILAI_BNG,'" . $tahun_pajak . "' as TAHUN FROM (((DAT_OBJEK_PAJAK INNER JOIN REF_KECAMATAN ON DAT_OBJEK_PAJAK.KD_KECAMATAN = REF_KECAMATAN.KD_KECAMATAN) " . "INNER JOIN REF_KELURAHAN ON (DAT_OBJEK_PAJAK.KD_KECAMATAN = REF_KELURAHAN.KD_KECAMATAN) AND (DAT_OBJEK_PAJAK.KD_KELURAHAN = REF_KELURAHAN.KD_KELURAHAN)) INNER JOIN DAT_OP_BUMI ON (DAT_OBJEK_PAJAK.KD_PROPINSI = DAT_OP_BUMI.KD_PROPINSI) AND (DAT_OBJEK_PAJAK.KD_DATI2 = DAT_OP_BUMI.KD_DATI2) AND (DAT_OBJEK_PAJAK.KD_KECAMATAN = DAT_OP_BUMI.KD_KECAMATAN) AND (DAT_OBJEK_PAJAK.KD_KELURAHAN = DAT_OP_BUMI.KD_KELURAHAN) AND (DAT_OBJEK_PAJAK.KD_BLOK = DAT_OP_BUMI.KD_BLOK) AND (DAT_OBJEK_PAJAK.NO_URUT = DAT_OP_BUMI.NO_URUT) AND (DAT_OBJEK_PAJAK.KD_JNS_OP = DAT_OP_BUMI.KD_JNS_OP))" . "LEFT JOIN DAT_OP_BANGUNAN ON (DAT_OBJEK_PAJAK.KD_PROPINSI = DAT_OP_BANGUNAN.KD_PROPINSI) AND (DAT_OBJEK_PAJAK.KD_DATI2 = DAT_OP_BANGUNAN.KD_DATI2) AND (DAT_OBJEK_PAJAK.KD_KECAMATAN = DAT_OP_BANGUNAN.KD_KECAMATAN) AND (DAT_OBJEK_PAJAK.KD_KELURAHAN = DAT_OP_BANGUNAN.KD_KELURAHAN) AND (DAT_OBJEK_PAJAK.KD_BLOK = DAT_OP_BANGUNAN.KD_BLOK) AND (DAT_OBJEK_PAJAK.NO_URUT = DAT_OP_BANGUNAN.NO_URUT) AND (DAT_OBJEK_PAJAK.KD_JNS_OP = DAT_OP_BANGUNAN.KD_JNS_OP) " . "WHERE DAT_OBJEK_PAJAK.KD_KECAMATAN ='" . $KD_KECAMATAN . "' GROUP BY DAT_OBJEK_PAJAK.KD_PROPINSI, DAT_OBJEK_PAJAK.KD_DATI2, DAT_OBJEK_PAJAK.KD_Kecamatan, DAT_OBJEK_PAJAK.KD_KELURAHAN, DAT_OP_BUMI.KD_BLOK, DAT_OP_BUMI.NO_URUT, DAT_OP_BUMI.KD_JNS_OP, DAT_OP_BUMI.NO_BUMI, DAT_OBJEK_PAJAK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, DAT_OP_BUMI.NILAI_SISTEM_BUMI UNION ALL " . "SELECT C_OBJEK.KD_PROPINSI, C_OBJEK.KD_DATI2, C_OBJEK.KD_Kecamatan, C_OBJEK.KD_KELURAHAN, C_OBJEK.KD_BLOK, C_OBJEK.NO_URUT, C_OBJEK.KD_JNS_OP, C_BUMI.NO_BUMI, C_OBJEK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, C_BUMI.NILAI_SISTEM_BUMI, Count(C_BANGUNAN.NO_BNG) AS JUM_BNG, Sum(C_BANGUNAN.LUAS_BNG) AS TOT_LUAS_BNG, Sum(C_BANGUNAN.NILAI_SISTEM_BNG) AS TOT_NILAI_BNG,'" . ($tahun_pajak-1) . "' as TAHUN FROM (((C_OBJEK INNER JOIN REF_KECAMATAN ON C_OBJEK.KD_KECAMATAN = REF_KECAMATAN.KD_KECAMATAN)" . "INNER JOIN REF_KELURAHAN ON (C_OBJEK.KD_KECAMATAN = REF_KELURAHAN.KD_KECAMATAN) AND (C_OBJEK.KD_KELURAHAN = REF_KELURAHAN.KD_KELURAHAN)) INNER JOIN C_BUMI ON (C_OBJEK.KD_KECAMATAN = C_BUMI.KD_KECAMATAN) AND (C_OBJEK.KD_KELURAHAN = C_BUMI.KD_KELURAHAN) AND (C_OBJEK.KD_BLOK = C_BUMI.KD_BLOK) AND (C_OBJEK.NO_URUT = C_BUMI.NO_URUT) AND (C_OBJEK.KD_JNS_OP = C_BUMI.KD_JNS_OP)) LEFT JOIN C_BANGUNAN ON (C_OBJEK.KD_KECAMATAN = C_BANGUNAN.KD_KECAMATAN) AND (C_OBJEK.KD_KELURAHAN = C_BANGUNAN.KD_KELURAHAN) AND (C_OBJEK.KD_BLOK = C_BANGUNAN.KD_BLOK) AND (C_OBJEK.NO_URUT = C_BANGUNAN.NO_URUT) AND (C_OBJEK.KD_JNS_OP = C_BANGUNAN.KD_JNS_OP)" . "WHERE C_OBJEK.KD_KECAMATAN ='" . $KD_KECAMATAN . "' GROUP BY C_OBJEK.KD_PROPINSI, C_OBJEK.KD_DATI2, C_OBJEK.KD_Kecamatan, C_OBJEK.KD_KELURAHAN, C_OBJEK.KD_BLOK, C_OBJEK.NO_URUT, C_OBJEK.KD_JNS_OP, C_BUMI.NO_BUMI, C_OBJEK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, C_BUMI.NILAI_SISTEM_BUMI";
      
        
}else{

    $C_STR = "SELECT DAT_OBJEK_PAJAK.KD_PROPINSI, DAT_OBJEK_PAJAK.KD_DATI2, DAT_OBJEK_PAJAK.KD_Kecamatan, DAT_OBJEK_PAJAK.KD_KELURAHAN, DAT_OP_BUMI.KD_BLOK, DAT_OP_BUMI.NO_URUT, DAT_OP_BUMI.KD_JNS_OP, DAT_OP_BUMI.NO_BUMI, DAT_OBJEK_PAJAK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, DAT_OP_BUMI.NILAI_SISTEM_BUMI, Count(DAT_OP_BANGUNAN.NO_BNG) AS JUM_BNG, Sum(DAT_OP_BANGUNAN.LUAS_BNG) AS TOT_LUAS_BNG, Sum(DAT_OP_BANGUNAN.NILAI_SISTEM_BNG) AS TOT_NILAI_BNG,'" . $tahun_pajak . "' as TAHUN FROM (((DAT_OBJEK_PAJAK INNER JOIN REF_KECAMATAN ON DAT_OBJEK_PAJAK.KD_KECAMATAN = REF_KECAMATAN.KD_KECAMATAN) " . "INNER JOIN REF_KELURAHAN ON (DAT_OBJEK_PAJAK.KD_KECAMATAN = REF_KELURAHAN.KD_KECAMATAN) AND (DAT_OBJEK_PAJAK.KD_KELURAHAN = REF_KELURAHAN.KD_KELURAHAN)) INNER JOIN DAT_OP_BUMI ON (DAT_OBJEK_PAJAK.KD_PROPINSI = DAT_OP_BUMI.KD_PROPINSI) AND (DAT_OBJEK_PAJAK.KD_DATI2 = DAT_OP_BUMI.KD_DATI2) AND (DAT_OBJEK_PAJAK.KD_KECAMATAN = DAT_OP_BUMI.KD_KECAMATAN) AND (DAT_OBJEK_PAJAK.KD_KELURAHAN = DAT_OP_BUMI.KD_KELURAHAN) AND (DAT_OBJEK_PAJAK.KD_BLOK = DAT_OP_BUMI.KD_BLOK) AND (DAT_OBJEK_PAJAK.NO_URUT = DAT_OP_BUMI.NO_URUT) AND (DAT_OBJEK_PAJAK.KD_JNS_OP = DAT_OP_BUMI.KD_JNS_OP))" . "LEFT JOIN DAT_OP_BANGUNAN ON (DAT_OBJEK_PAJAK.KD_PROPINSI = DAT_OP_BANGUNAN.KD_PROPINSI) AND (DAT_OBJEK_PAJAK.KD_DATI2 = DAT_OP_BANGUNAN.KD_DATI2) AND (DAT_OBJEK_PAJAK.KD_KECAMATAN = DAT_OP_BANGUNAN.KD_KECAMATAN) AND (DAT_OBJEK_PAJAK.KD_KELURAHAN = DAT_OP_BANGUNAN.KD_KELURAHAN) AND (DAT_OBJEK_PAJAK.KD_BLOK = DAT_OP_BANGUNAN.KD_BLOK) AND (DAT_OBJEK_PAJAK.NO_URUT = DAT_OP_BANGUNAN.NO_URUT) AND (DAT_OBJEK_PAJAK.KD_JNS_OP = DAT_OP_BANGUNAN.KD_JNS_OP) " . "WHERE DAT_OBJEK_PAJAK.KD_KECAMATAN ='" . $KD_KECAMATAN . "' and DAT_OBJEK_PAJAK.KD_KELURAHAN='" . $KD_KELURAHAN . "' GROUP BY DAT_OBJEK_PAJAK.KD_PROPINSI, DAT_OBJEK_PAJAK.KD_DATI2, DAT_OBJEK_PAJAK.KD_Kecamatan, DAT_OBJEK_PAJAK.KD_KELURAHAN, DAT_OP_BUMI.KD_BLOK, DAT_OP_BUMI.NO_URUT, DAT_OP_BUMI.KD_JNS_OP, DAT_OP_BUMI.NO_BUMI, DAT_OBJEK_PAJAK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, DAT_OP_BUMI.NILAI_SISTEM_BUMI UNION ALL " . "SELECT C_OBJEK.KD_PROPINSI, C_OBJEK.KD_DATI2, C_OBJEK.KD_Kecamatan, C_OBJEK.KD_KELURAHAN, C_OBJEK.KD_BLOK, C_OBJEK.NO_URUT, C_OBJEK.KD_JNS_OP, C_BUMI.NO_BUMI, C_OBJEK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, C_BUMI.NILAI_SISTEM_BUMI, Count(C_BANGUNAN.NO_BNG) AS JUM_BNG, Sum(C_BANGUNAN.LUAS_BNG) AS TOT_LUAS_BNG, Sum(C_BANGUNAN.NILAI_SISTEM_BNG) AS TOT_NILAI_BNG,'" . ($tahun_pajak-1) . "' as TAHUN FROM (((C_OBJEK INNER JOIN REF_KECAMATAN ON C_OBJEK.KD_KECAMATAN = REF_KECAMATAN.KD_KECAMATAN)" . "INNER JOIN REF_KELURAHAN ON (C_OBJEK.KD_KECAMATAN = REF_KELURAHAN.KD_KECAMATAN) AND (C_OBJEK.KD_KELURAHAN = REF_KELURAHAN.KD_KELURAHAN)) INNER JOIN C_BUMI ON (C_OBJEK.KD_KECAMATAN = C_BUMI.KD_KECAMATAN) AND (C_OBJEK.KD_KELURAHAN = C_BUMI.KD_KELURAHAN) AND (C_OBJEK.KD_BLOK = C_BUMI.KD_BLOK) AND (C_OBJEK.NO_URUT = C_BUMI.NO_URUT) AND (C_OBJEK.KD_JNS_OP = C_BUMI.KD_JNS_OP)) LEFT JOIN C_BANGUNAN ON (C_OBJEK.KD_KECAMATAN = C_BANGUNAN.KD_KECAMATAN) AND (C_OBJEK.KD_KELURAHAN = C_BANGUNAN.KD_KELURAHAN) AND (C_OBJEK.KD_BLOK = C_BANGUNAN.KD_BLOK) AND (C_OBJEK.NO_URUT = C_BANGUNAN.NO_URUT) AND (C_OBJEK.KD_JNS_OP = C_BANGUNAN.KD_JNS_OP)" . "WHERE C_OBJEK.KD_KECAMATAN ='" . $KD_KECAMATAN . "' and C_OBJEK.KD_KELURAHAN='" . $KD_KELURAHAN . "' GROUP BY C_OBJEK.KD_PROPINSI, C_OBJEK.KD_DATI2, C_OBJEK.KD_Kecamatan, C_OBJEK.KD_KELURAHAN, C_OBJEK.KD_BLOK, C_OBJEK.NO_URUT, C_OBJEK.KD_JNS_OP, C_BUMI.NO_BUMI, C_OBJEK.TOTAL_LUAS_BUMI, REF_KECAMATAN.NM_KECAMATAN, REF_KELURAHAN.NM_KELURAHAN, C_BUMI.NILAI_SISTEM_BUMI";

}

$datas = $qb->rawQuery($C_STR)->get();


$datas_new = [];

foreach ($datas as $key => $value) {

    if(array_key_exists($value['TAHUN'],$datas_new)){

        $datas_new[$value['TAHUN']]['TOTAL'] = [
            'JLH_BUMI'=> $datas_new[$value['TAHUN']]['TOTAL']['JLH_BUMI'] + $value['NO_BUMI'],
            'LUAS_BUMI'=> $datas_new[$value['TAHUN']]['TOTAL']['LUAS_BUMI'] + $value['TOTAL_LUAS_BUMI'],
            'NILAI_SISTEM_BUMI'=> $datas_new[$value['TAHUN']]['TOTAL']['NILAI_SISTEM_BUMI'] + $value['NILAI_SISTEM_BUMI'],
    
            'JLH_BNG'=> $datas_new[$value['TAHUN']]['TOTAL']['JLH_BNG'] + $value['JUM_BNG'],
            'LUAS_BNG'=> $datas_new[$value['TAHUN']]['TOTAL']['LUAS_BNG'] + $value['TOT_LUAS_BNG'],
            'NILAI_SISTEM_BNG'=> $datas_new[$value['TAHUN']]['TOTAL']['NILAI_SISTEM_BNG'] + $value['TOT_NILAI_BNG'],
        ];


    }else{
        $datas_new[$value['TAHUN']]['TOTAL'] = [
            'JLH_BUMI'=> $value['NO_BUMI'] ?? 0,
            'LUAS_BUMI'=> $value['TOTAL_LUAS_BUMI'] ?? 0,
            'NILAI_SISTEM_BUMI'=> $value['NILAI_SISTEM_BUMI'] ?? 0,

            'JLH_BNG'=> $value['JUM_BNG'] ?? 0,
            'LUAS_BNG'=> $value['TOT_LUAS_BNG'] ?? 0,
            'NILAI_SISTEM_BNG'=> $value['TOT_NILAI_BNG'] ?? 0,
        ];
    }

    // if($value['TAHUN'] == $tahun_pajak){

        if(array_key_exists('KECAMATANS',$datas_new[$value['TAHUN']])){

            if(array_key_exists($value['NM_KECAMATAN'],$datas_new[$value['TAHUN']]['KECAMATANS'])){

                if(array_key_exists($value['NM_KELURAHAN'],$datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'])){

                    $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'][$value['NM_KELURAHAN']] = [
                        'JLH_BUMI'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'][$value['NM_KELURAHAN']]['JLH_BUMI'] + $value['NO_BUMI'],
                        'LUAS_BUMI'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'][$value['NM_KELURAHAN']]['LUAS_BUMI'] + $value['TOTAL_LUAS_BUMI'],
                        'NILAI_SISTEM_BUMI'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'][$value['NM_KELURAHAN']]['NILAI_SISTEM_BUMI'] + $value['NILAI_SISTEM_BUMI'],
            
                        'JLH_BNG'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'][$value['NM_KELURAHAN']]['JLH_BNG'] + $value['JUM_BNG'],
                        'LUAS_BNG'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'][$value['NM_KELURAHAN']]['LUAS_BNG'] + $value['TOT_LUAS_BNG'],
                        'NILAI_SISTEM_BNG'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'][$value['NM_KELURAHAN']]['NILAI_SISTEM_BNG'] + $value['TOT_NILAI_BNG'],
                    ];

                }else{

                $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'][$value['NM_KELURAHAN']] = [
                        'JLH_BUMI'=> $value['NO_BUMI'] ?? 0,
                        'LUAS_BUMI'=> $value['TOTAL_LUAS_BUMI'] ?? 0,
                        'NILAI_SISTEM_BUMI'=> $value['NILAI_SISTEM_BUMI'] ?? 0,

                        'JLH_BNG'=> $value['JUM_BNG'] ?? 0,
                        'LUAS_BNG'=> $value['TOT_LUAS_BNG'] ?? 0,
                        'NILAI_SISTEM_BNG'=> $value['TOT_NILAI_BNG'] ?? 0,
                    ];

                    
                }
                
                $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]["JUMLAH"] = [
                    'JLH_BUMI'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['JUMLAH']['JLH_BUMI'] + $value['NO_BUMI'],
                    'LUAS_BUMI'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['JUMLAH']['LUAS_BUMI'] + $value['TOTAL_LUAS_BUMI'],
                    'NILAI_SISTEM_BUMI'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['JUMLAH']['NILAI_SISTEM_BUMI'] + $value['NILAI_SISTEM_BUMI'],

                    'JLH_BNG'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['JUMLAH']['JLH_BNG'] + $value['JUM_BNG'],
                    'LUAS_BNG'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['JUMLAH']['LUAS_BNG'] + $value['TOT_LUAS_BNG'],
                    'NILAI_SISTEM_BNG'=> $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['JUMLAH']['NILAI_SISTEM_BNG'] + $value['TOT_NILAI_BNG'],
                ];

            }else{

                $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'][$value['NM_KELURAHAN']] = [
                    'JLH_BUMI'=> $value['NO_BUMI'] ?? 0,
                    'LUAS_BUMI'=> $value['TOTAL_LUAS_BUMI'] ?? 0,
                    'NILAI_SISTEM_BUMI'=> $value['NILAI_SISTEM_BUMI'] ?? 0,

                    'JLH_BNG'=> $value['JUM_BNG'] ?? 0,
                    'LUAS_BNG'=> $value['TOT_LUAS_BNG'] ?? 0,
                    'NILAI_SISTEM_BNG'=> $value['TOT_NILAI_BNG'] ?? 0,
                ];

                $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]["JUMLAH"] = [
                    'JLH_BUMI'=> $value['NO_BUMI'] ?? 0,
                    'LUAS_BUMI'=> $value['TOTAL_LUAS_BUMI'] ?? 0,
                    'NILAI_SISTEM_BUMI'=> $value['NILAI_SISTEM_BUMI'] ?? 0,

                    'JLH_BNG'=> $value['JUM_BNG'] ?? 0,
                    'LUAS_BNG'=> $value['TOT_LUAS_BNG'] ?? 0,
                    'NILAI_SISTEM_BNG'=> $value['TOT_NILAI_BNG'] ?? 0,
                ];
            }

        }else{
            $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]['KELURAHANS'][$value['NM_KELURAHAN']] = [
                'JLH_BUMI'=> $value['NO_BUMI'] ?? 0,
                'LUAS_BUMI'=> $value['TOTAL_LUAS_BUMI'] ?? 0,
                'NILAI_SISTEM_BUMI'=> $value['NILAI_SISTEM_BUMI'] ?? 0,

                'JLH_BNG'=> $value['JUM_BNG'] ?? 0,
                'LUAS_BNG'=> $value['TOT_LUAS_BNG'] ?? 0,
                'NILAI_SISTEM_BNG'=> $value['TOT_NILAI_BNG'] ?? 0,
            ];

            $datas_new[$value['TAHUN']]['KECAMATANS'][$value['NM_KECAMATAN']]["JUMLAH"] = [
                'JLH_BUMI'=> $value['NO_BUMI'] ?? 0,
                'LUAS_BUMI'=> $value['TOTAL_LUAS_BUMI'] ?? 0,
                'NILAI_SISTEM_BUMI'=> $value['NILAI_SISTEM_BUMI'] ?? 0,

                'JLH_BNG'=> $value['JUM_BNG'] ?? 0,
                'LUAS_BNG'=> $value['TOT_LUAS_BNG'] ?? 0,
                'NILAI_SISTEM_BNG'=> $value['TOT_NILAI_BNG'] ?? 0,
            ];
        }
    
    // }
}