<?php

require '../helpers/QueryBuilder.php';

$msg = get_flash_msg('success');
$qb = new QueryBuilder();
$qb1 = new QueryBuilder();

if(request() == 'POST'){
    foreach($_POST['HARGA_BARU'] as $key => $hb){
        if($hb){

            $keys = explode('-',$key);

            $upd = $qb->update("HRG_RESOURCE",['HRG_RESOURCE'=>$hb])->where('THN_HRG_RESOURCE',$_GET['year'])->where('KD_RESOURCE',$keys[0])->where('KD_GROUP_RESOURCE',$keys[1])->exec();
        }
    }

    set_flash_msg(['success'=>'Data Updated']);
    header("location:index.php?page=builder/update-resources/index&year=$_GET[year]&group=$_GET[group]");
    return;
}

$years = []; 
for($i = 0 ; $i<100;$i++){
    $years[] = date("Y",strtotime("-$i year"));
}

$year = date("Y");

if(isset($_GET['year']) && $_GET['year']){
    $year = $_GET['year'];
}

$strGR = "Select * From GROUP_RESOURCE ORDER BY KD_GROUP_RESOURCE ASC ";

$groups = $qb->rawQuery($strGR)->get();

for($i=0;$i<=1;$i++):

$y = $year - $i;

$sql = "SELECT GROUP_RESOURCE.KD_GROUP_RESOURCE, GROUP_RESOURCE.NM_GROUP_RESOURCE, ITEM_RESOURCE.KD_RESOURCE, ITEM_RESOURCE.NM_RESOURCE, ITEM_RESOURCE.SATUAN_RESOURCE, HRG_RESOURCE.HRG_RESOURCE, HRG_RESOURCE.THN_HRG_RESOURCE FROM (GROUP_RESOURCE INNER JOIN HRG_RESOURCE ON GROUP_RESOURCE.KD_GROUP_RESOURCE = HRG_RESOURCE.KD_GROUP_RESOURCE) INNER JOIN ITEM_RESOURCE ON (HRG_RESOURCE.KD_GROUP_RESOURCE = ITEM_RESOURCE.KD_GROUP_RESOURCE) AND (HRG_RESOURCE.KD_RESOURCE = ITEM_RESOURCE.KD_RESOURCE) WHERE (((HRG_RESOURCE.THN_HRG_RESOURCE)='" . $y . "'))";


if(isset($_GET['filter'])){
    
    if($_GET['group']){
        
        $sql = "SELECT GROUP_RESOURCE.KD_GROUP_RESOURCE, GROUP_RESOURCE.NM_GROUP_RESOURCE, ITEM_RESOURCE.KD_RESOURCE, ITEM_RESOURCE.NM_RESOURCE, ITEM_RESOURCE.SATUAN_RESOURCE, HRG_RESOURCE.HRG_RESOURCE, HRG_RESOURCE.THN_HRG_RESOURCE FROM (GROUP_RESOURCE INNER JOIN HRG_RESOURCE ON GROUP_RESOURCE.KD_GROUP_RESOURCE = HRG_RESOURCE.KD_GROUP_RESOURCE) INNER JOIN ITEM_RESOURCE ON (HRG_RESOURCE.KD_GROUP_RESOURCE = ITEM_RESOURCE.KD_GROUP_RESOURCE) AND (HRG_RESOURCE.KD_RESOURCE = ITEM_RESOURCE.KD_RESOURCE) WHERE GROUP_RESOURCE.KD_GROUP_RESOURCE='".$_GET['group']."' and (((HRG_RESOURCE.THN_HRG_RESOURCE)='" . $y . "'))";

    }else{
        
        $sql = "SELECT GROUP_RESOURCE.KD_GROUP_RESOURCE, GROUP_RESOURCE.NM_GROUP_RESOURCE, ITEM_RESOURCE.KD_RESOURCE, ITEM_RESOURCE.NM_RESOURCE, ITEM_RESOURCE.SATUAN_RESOURCE, HRG_RESOURCE.HRG_RESOURCE, HRG_RESOURCE.THN_HRG_RESOURCE FROM (GROUP_RESOURCE INNER JOIN HRG_RESOURCE ON GROUP_RESOURCE.KD_GROUP_RESOURCE = HRG_RESOURCE.KD_GROUP_RESOURCE) INNER JOIN ITEM_RESOURCE ON (HRG_RESOURCE.KD_GROUP_RESOURCE = ITEM_RESOURCE.KD_GROUP_RESOURCE) AND (HRG_RESOURCE.KD_RESOURCE = ITEM_RESOURCE.KD_RESOURCE) WHERE (((HRG_RESOURCE.THN_HRG_RESOURCE)='" . $y . "'))";
    }
}

$datas = $qb->rawQuery($sql)->orderBy('GROUP_RESOURCE.KD_GROUP_RESOURCE')->get();

if(!empty($datas)) break;

endfor;
